# Generated by Django 4.2.23 on 2026-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_people_is_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='art_work_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='art_work_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='profile_picture_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='profile_picture_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
