# Generated by Django 4.2.23 on 2026-07-31 08:32

from django.db import migrations, models
import gaatha.utils


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_backfill_file_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='art_work',
            field=models.FileField(blank=True, upload_to='people/art-works', validators=[gaatha.utils.FileSizeValidator()], verbose_name='Art Work'),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='people/profile-pictures', validators=[gaatha.utils.FileSizeValidator()], verbose_name='Profile Picture'),
        ),
    ]
