"""
Django settings for gaatha project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import environ

from gaatha.logging import skip_health_probe_logs

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    DEBUG=(bool, False),
    DJANGO_SECRET_KEY=str,
    ADDITIONAL_ALLOWED_HOSTS=(list, []),
    APP_ENVIRONMENT=str,
    DB_NAME=str,
    DB_USER=str,
    DB_PWD=str,
    DB_HOST=str,
    DB_PORT=str,
    LANGUAGE_CODE=str,
    TIME_ZONE=(str, "UTC"),
    APP_DOMAIN=str,  # Eg: https://api.example.org
    FRONTEND_DOMAIN=str,  # Eg: https://web.example.org
    SESSION_COOKIE_DOMAIN=str,  # .example.com
    CSRF_COOKIE_DOMAIN=str,  # .example.com
    ADDITIONAL_TRUSTED_ORIGINS=(list, []),
    # Static, Media configs
    DJANGO_STATIC_URL=(str, "/static/"),
    DJANGO_MEDIA_URL=(str, "/media/"),
    # File System
    DJANGO_STATIC_ROOT=(str, BASE_DIR / "assets/static"),
    DJANGO_MEDIA_ROOT=(str, BASE_DIR / "assets/media"),
    # Aws-S3
    AWS_S3_ENABLED=(bool, False),
    AWS_S3_ENDPOINT_URL=(str, None),
    AWS_S3_ACCESS_KEY_ID=str,
    AWS_S3_SECRET_ACCESS_KEY=str,
    AWS_S3_REGION_NAME=str,
    AWS_S3_MEDIA_BUCKET_NAME=str,
    AWS_S3_STATIC_BUCKET_NAME=str,
    # django-health-check (/health-check/)
    # DISK_USAGE_MAX is a str so an empty/null value can map to None (skip); see below.
    HEALTH_CHECK_DISK_USAGE_MAX=(str, "80"),  # percent; empty/"none"/"null" -> skip disk check
    HEALTH_CHECK_MEMORY_MIN=(int, 100),  # MB
    HEALTH_CHECK_SKIP_STORAGE=(bool, False),
)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
APP_DOMAIN = env.url("APP_DOMAIN")
FRONTEND_DOMAIN = env.url("FRONTEND_DOMAIN")
APP_ENVIRONMENT = env("APP_ENVIRONMENT").upper()

ALLOWED_HOSTS = [
    'server',
    *env('ADDITIONAL_ALLOWED_HOSTS'),
    APP_DOMAIN.hostname,
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # local apps
    'apps.work',
    'apps.people',
    # thirdparty apps
    'banjo_utils',
    # django-health-check: outward-facing /health-check/ endpoint for the external
    # monitor (distinct from banjo_utils' pod-internal /healthz probes). Only the
    # checkers whose dependency this project ships are enabled: DB, cache (Django's
    # default cache framework), unapplied migrations, and disk/memory (psutil).
    # health_check.storage is appended below unless HEALTH_CHECK_SKIP_STORAGE is set.
    # Skipped: health_check.contrib.redis (no Redis cache/broker wired — no CACHES,
    # no REDIS_URL) and health_check.contrib.rabbitmq (no RabbitMQ/AMQP broker).
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.contrib.migrations',
    'health_check.contrib.psutil',
    'strawberry.django',
    'tinymce',
]

# health_check.storage writes a small probe file to the default file storage on every
# /health-check/ poll. Enabled by default; set HEALTH_CHECK_SKIP_STORAGE=true to omit it
# — e.g. environments backed by object storage the monitor should not write to (used
# with minio, skipped with S3).
if not env('HEALTH_CHECK_SKIP_STORAGE'):
    INSTALLED_APPS.append('health_check.storage')

MIDDLEWARE = [
    # banjo_utils HealthProbeMiddleware serves pod-local /healthz/live/ and
    # /healthz/ready/ (bypassing ALLOWED_HOSTS); keep it first.
    'banjo_utils.health.HealthProbeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gaatha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gaatha.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env('DB_NAME'),
        "USER": env('DB_USER'),
        "PASSWORD": env('DB_PWD'),
        "HOST": env('DB_HOST'),
        "PORT": env('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE')

TIME_ZONE = env('TIME_ZONE')

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
MEDIA_URL = env("DJANGO_MEDIA_URL")
STATIC_URL = env("DJANGO_STATIC_URL")

if env("AWS_S3_ENABLED"):
    AWS_S3_CONFIG_OPTIONS = {
        "endpoint_url": env("AWS_S3_ENDPOINT_URL"),
        "access_key": env("AWS_S3_ACCESS_KEY_ID"),
        "secret_key": env("AWS_S3_SECRET_ACCESS_KEY"),
        "region_name": env("AWS_S3_REGION_NAME"),
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                **AWS_S3_CONFIG_OPTIONS,
                "bucket_name": env("AWS_S3_MEDIA_BUCKET_NAME"),
                "querystring_auth": False,
                "location": "media/",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                **AWS_S3_CONFIG_OPTIONS,
                "bucket_name": env("AWS_S3_STATIC_BUCKET_NAME"),
                "querystring_auth": False,
                "location": "static/",
                "file_overwrite": True,
            },
        },
    }
else:
    STATIC_ROOT = env("DJANGO_STATIC_ROOT")
    MEDIA_ROOT = env("DJANGO_MEDIA_ROOT")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

# Security Header configuration

TRUSTED_ORIGINS = [
    APP_DOMAIN.geturl(),
    FRONTEND_DOMAIN.geturl(),
    *env("ADDITIONAL_TRUSTED_ORIGINS"),
]

SESSION_COOKIE_NAME = f"GAATHA-{APP_ENVIRONMENT}-SESSIONID"
CSRF_COOKIE_NAME = f"GAATHA-{APP_ENVIRONMENT}-CSRFTOKEN"
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
CSP_DEFAULT_SRC = ["'self'"]
SECURE_REFERRER_POLICY = "same-origin"
if APP_DOMAIN.scheme == "https":
    SESSION_COOKIE_NAME = f"__Secure-{SESSION_COOKIE_NAME}"
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = TRUSTED_ORIGINS

# -- https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SESSION_COOKIE_DOMAIN
SESSION_COOKIE_DOMAIN = env("SESSION_COOKIE_DOMAIN")
# https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-domain
CSRF_COOKIE_DOMAIN = env("CSRF_COOKIE_DOMAIN")


# CORS
CORS_ALLOWED_ORIGINS = TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = TRUSTED_ORIGINS

CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r"(^/media/.*$)|(^/graphql/$)"
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "baggage",
)


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "menubar": "file edit view insert format tools table help",
    "plugins": (
        "advlist autolink lists link image charmap print preview anchor "
        "searchreplace visualblocks code fullscreen insertdatetime media "
        "table paste code help wordcount spellchecker"
    ),
    "toolbar": (
        "undo redo | bold italic underline strikethrough | fontselect "
        "fontsizeselect formatselect | alignleft aligncenter alignright "
        "alignjustify | outdent indent |  numlist bullist checklist | "
        "forecolor backcolor casechange permanentpen formatpainter "
        "removeformat | pagebreak | charmap emoticons | "
        "fullscreen  preview save print | "
        "insertfile image media pageembed template link anchor codesample | "
        "a11ycheck ltr rtl | showcomments addcomment code"
    ),
    "custom_undo_redo_levels": 10,
}

# banjo_utils HealthProbeMiddleware — pod-local k8s probe endpoints
BANJO_HEALTH_PROBE_LIVE_URL = "/healthz/live/"
BANJO_HEALTH_PROBE_READY_URL = "/healthz/ready/"

# django-health-check exposes /health-check/. Unlike the /healthz probes above,
# it is a normal Django view: subject to ALLOWED_HOSTS (the external monitor must
# request a host in ALLOWED_HOSTS / ADDITIONAL_ALLOWED_HOSTS), publicly reachable
# (no auth middleware gates it), and its request logs are NOT suppressed (the
# probe-log filter matches only the /healthz paths).
HEALTHCHECK_CACHE_KEY = "app_healthcheck_key"
# psutil thresholds. The disk check is skippable: an empty / "none" / "null"
# HEALTH_CHECK_DISK_USAGE_MAX resolves to None, which makes health_check.contrib.psutil
# skip registering the disk check entirely (the Disk line disappears from /health-check/
# while Memory still reports) — the psutil app's ready() drops DiskUsage when
# HEALTH_CHECK["DISK_USAGE_MAX"] is None. Unset falls back to the 80% default (disk check
# on). HEALTH_CHECK_MEMORY_MIN is the min available memory in MB (default 100).
_disk_usage_max = env('HEALTH_CHECK_DISK_USAGE_MAX').strip()
HEALTH_CHECK = {
    "DISK_USAGE_MAX": int(_disk_usage_max) if _disk_usage_max and _disk_usage_max.lower() not in ('none', 'null') else None,
    "MEMORY_MIN": env('HEALTH_CHECK_MEMORY_MIN'),  # MB (env HEALTH_CHECK_MEMORY_MIN)
}

# Drop successful (2xx) request-line logs for the health-probe paths so the
# k8s probes (firing every few seconds) don't flood the logs. 4xx/5xx stay visible.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "skip_health_probes": {
            "()": "django.utils.log.CallbackFilter",
            "callback": skip_health_probe_logs,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["skip_health_probes"],
        },
    },
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
