# Generated by Django 4.2.23 on 2026-07-31 08:32

from django.db import migrations, models
import gaatha.utils


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_backfill_file_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='art_work',
            field=models.FileField(blank=True, null=True, upload_to='work/art-works', validators=[gaatha.utils.FileSizeValidator()]),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='work/cover-images', validators=[gaatha.utils.FileSizeValidator()], verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(upload_to='work-image/images/', validators=[gaatha.utils.FileSizeValidator()], verbose_name='Image'),
        ),
    ]
